package constants

const (
	SALUDO = "HOLA MUNDO"

	// system envs
	ENVIRONMENT_TYPE = "ENVIRONMENT_TYPE"
	LOGMODE          = true
	BASE_PATH        = "BASE_PATH"
	AUTHOR           = "Alex Figueroa"
	ORIGIN           = "local"
	APP              = "Demo GO"
	PORT_SERVER      = "PORT_SERVER"

	// kafka
	KAFKA_BROKERS  = "KAFKA_BROKERS"
	KAFKA_GROUP_ID = "KAFKA_GROUP_ID"
	KAFKA_USERNAME = "KAFKA_USERNAME"
	KAFKA_PASSWORD = "KAFKA_PASSWORD"

	// topicos
	TOPIC_DEMO = "TOPIC_DEMO"

	// mongo
	MONGO            = "mongodb"
	MONGODB_HOST     = "MONGODB_HOST"
	MONGODB_PORT     = "MONGODB_PORT"
	MONGODB_DATABASE = "MONGODB_DATABASE"
	MONGODB_USERNAME = "MONGODB_USERNAME"
	MONGODB_PASSWORD = "MONGODB_PASSWORD"

	// postgres
	POSTGRESQL        = "postgres"
	POSTGRES_HOST     = "POSTGRES_HOST"
	POSTGRES_PORT     = "POSTGRES_PORT"
	POSTGRES_DATABASE = "POSTGRES_DATABASE"
	POSTGRES_USERNAME = "POSTGRES_USERNAME"
	POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
)
